import type { Collection, Entry } from '../../engine/types'

/**
 * The SRD 5.1 spell list.
 *
 * Written as compact tuples rather than objects: at three hundred-odd spells,
 * the tuple form is far easier to scan, diff, and correct than the same data
 * spread over ten thousand lines of JSON.
 *
 * Tuple order: name, level, school, classes, casting time, range, components,
 * duration, effect. Classes use single letters:
 *   b bard · c cleric · d druid · p paladin · r ranger · s sorcerer
 *   k warlock · w wizard
 */

type SpellTuple = [
  name: string,
  level: number,
  school: string,
  classes: string,
  time: string,
  range: string,
  components: string,
  duration: string,
  text: string,
]

const CLASS_BY_LETTER: Record<string, string> = {
  b: 'bard',
  c: 'cleric',
  d: 'druid',
  p: 'paladin',
  r: 'ranger',
  s: 'sorcerer',
  k: 'warlock',
  w: 'wizard',
}

const SCHOOLS: Record<string, string> = {
  A: 'Abjuration',
  C: 'Conjuration',
  D: 'Divination',
  E: 'Enchantment',
  V: 'Evocation',
  I: 'Illusion',
  N: 'Necromancy',
  T: 'Transmutation',
}

const spells: SpellTuple[] = [
  // ---------------------------------------------------------------- cantrips
  ['Acid Splash', 0, 'C', 'sw', '1 action', '60 ft.', 'V, S', 'Instantaneous', 'Hurl a bubble of acid at one or two creatures within 5 feet of each other; DEX save or 1d6 acid damage.'],
  ['Blade Ward', 0, 'A', 'bskw', '1 action', 'Self', 'V, S', '1 round', 'You gain resistance to bludgeoning, piercing, and slashing damage from weapon attacks until the end of your next turn.'],
  ['Chill Touch', 0, 'N', 'skw', '1 action', '120 ft.', 'V, S', '1 round', 'Spectral hand deals 1d8 necrotic damage and prevents the target regaining hit points until your next turn.'],
  ['Dancing Lights', 0, 'I', 'bsw', '1 action', '120 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'Create up to four torch-sized lights you can move as a bonus action.'],
  ['Druidcraft', 0, 'T', 'd', '1 action', '30 ft.', 'V, S', 'Instantaneous', 'Predict the weather, bloom a flower, snuff or light a small flame, or make a harmless sensory effect.'],
  ['Eldritch Blast', 0, 'V', 'k', '1 action', '120 ft.', 'V, S', 'Instantaneous', 'A beam of crackling energy deals 1d10 force damage. You gain more beams at 5th, 11th, and 17th level.'],
  ['Fire Bolt', 0, 'V', 'sw', '1 action', '120 ft.', 'V, S', 'Instantaneous', 'Hurl a mote of fire for 1d10 fire damage; flammable objects ignite.'],
  ['Friends', 0, 'E', 'bskw', '1 action', 'Self', 'S, M', 'Concentration, up to 1 minute', 'You have advantage on Charisma checks against one non-hostile creature, which knows it was charmed afterwards.'],
  ['Guidance', 0, 'D', 'cd', '1 action', 'Touch', 'V, S', 'Concentration, up to 1 minute', 'The target can add 1d4 to one ability check of its choice.'],
  ['Light', 0, 'V', 'bcsw', '1 action', 'Touch', 'V, M', '1 hour', 'An object sheds bright light in a 20-foot radius and dim light for 20 feet beyond.'],
  ['Mage Hand', 0, 'C', 'bskw', '1 action', '30 ft.', 'V, S', '1 minute', 'A spectral hand manipulates objects, opens containers, and carries up to 10 pounds.'],
  ['Mending', 0, 'T', 'bcdsw', '1 minute', 'Touch', 'V, S, M', 'Instantaneous', 'Repair a single break or tear in an object no larger than 1 foot across.'],
  ['Message', 0, 'T', 'bsw', '1 action', '120 ft.', 'V, S, M', '1 round', 'Whisper a message to a creature you can see; only it hears you, and it can reply in a whisper.'],
  ['Minor Illusion', 0, 'I', 'bskw', '1 action', '30 ft.', 'S, M', '1 minute', 'Create a sound or an image of an object no larger than a 5-foot cube.'],
  ['Poison Spray', 0, 'C', 'dskw', '1 action', '10 ft.', 'V, S', 'Instantaneous', 'A puff of noxious gas forces a CON save or 1d12 poison damage.'],
  ['Prestidigitation', 0, 'T', 'bskw', '1 action', '10 ft.', 'V, S', 'Up to 1 hour', 'A minor magical trick: a sensory effect, lighting a candle, cleaning an object, or a trinket.'],
  ['Produce Flame', 0, 'C', 'd', '1 action', 'Self', 'V, S', '10 minutes', 'A flame in your hand sheds light and can be hurled for 1d8 fire damage.'],
  ['Ray of Frost', 0, 'V', 'sw', '1 action', '60 ft.', 'V, S', 'Instantaneous', '1d8 cold damage and the target’s speed drops by 10 feet until your next turn.'],
  ['Resistance', 0, 'A', 'cd', '1 action', 'Touch', 'V, S, M', 'Concentration, up to 1 minute', 'The target can add 1d4 to one saving throw of its choice.'],
  ['Sacred Flame', 0, 'V', 'c', '1 action', '60 ft.', 'V, S', 'Instantaneous', 'Radiance descends on a creature; DEX save or 1d8 radiant damage, ignoring cover.'],
  ['Shillelagh', 0, 'T', 'd', '1 bonus action', 'Touch', 'V, S, M', '1 minute', 'A club or quarterstaff uses your spellcasting ability for attacks and deals 1d8 damage.'],
  ['Shocking Grasp', 0, 'V', 'sw', '1 action', 'Touch', 'V, S', 'Instantaneous', '1d8 lightning damage, and the target cannot take reactions until its next turn.'],
  ['Spare the Dying', 0, 'N', 'c', '1 action', 'Touch', 'V, S', 'Instantaneous', 'Stabilise a creature at 0 hit points.'],
  ['Thaumaturgy', 0, 'T', 'c', '1 action', '30 ft.', 'V', 'Up to 1 minute', 'A minor wonder: a booming voice, flickering flames, tremors, or doors flying open.'],
  ['Thorn Whip', 0, 'T', 'd', '1 action', '30 ft.', 'V, S, M', 'Instantaneous', 'A vine lashes out for 1d6 piercing damage and pulls the target up to 10 feet closer.'],
  ['True Strike', 0, 'D', 'bskw', '1 action', '30 ft.', 'S', 'Concentration, up to 1 round', 'You gain advantage on your first attack roll against the target on your next turn.'],
  ['Vicious Mockery', 0, 'E', 'b', '1 action', '60 ft.', 'V', 'Instantaneous', 'A string of insults; WIS save or 1d4 psychic damage and disadvantage on its next attack roll.'],

  // ------------------------------------------------------------------ level 1
  ['Alarm', 1, 'A', 'rw', '1 minute', '30 ft.', 'V, S, M', '8 hours', 'Ward an area; you receive a mental or audible alarm when a creature enters it.'],
  ['Animal Friendship', 1, 'E', 'bdr', '1 action', '30 ft.', 'V, S, M', '24 hours', 'Convince a beast you mean no harm; WIS save or it is charmed.'],
  ['Armor of Agathys', 1, 'A', 'k', '1 action', 'Self', 'V, S, M', '1 hour', 'Gain 5 temporary hit points; attackers in melee take 5 cold damage while they last.'],
  ['Arms of Hadar', 1, 'C', 'k', '1 action', 'Self (10-ft. radius)', 'V, S', 'Instantaneous', 'Tendrils lash out; STR save or 2d6 necrotic damage and no reactions until the target’s next turn.'],
  ['Bane', 1, 'E', 'bc', '1 action', '30 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'Up to three creatures subtract 1d4 from attack rolls and saving throws.'],
  ['Bless', 1, 'V', 'cp', '1 action', '30 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'Up to three creatures add 1d4 to attack rolls and saving throws.'],
  ['Burning Hands', 1, 'V', 'sw', '1 action', 'Self (15-ft. cone)', 'V, S', 'Instantaneous', 'A sheet of flame; DEX save or 3d6 fire damage, half on a success.'],
  ['Charm Person', 1, 'E', 'bdskw', '1 action', '30 ft.', 'V, S', '1 hour', 'A humanoid must make a WIS save or regard you as a friendly acquaintance.'],
  ['Chromatic Orb', 1, 'V', 'sw', '1 action', '90 ft.', 'V, S, M', 'Instantaneous', 'Hurl a 4-inch sphere of energy for 3d8 damage of a type you choose.'],
  ['Color Spray', 1, 'I', 'sw', '1 action', 'Self (15-ft. cone)', 'V, S, M', '1 round', 'Dazzling colours blind creatures totalling 6d10 hit points.'],
  ['Command', 1, 'E', 'cp', '1 action', '60 ft.', 'V', '1 round', 'A one-word command the target must obey on a failed WIS save.'],
  ['Comprehend Languages', 1, 'D', 'bskw', '1 action', 'Self', 'V, S, M', '1 hour', 'You understand the literal meaning of any spoken or written language.'],
  ['Create or Destroy Water', 1, 'T', 'cd', '1 action', '30 ft.', 'V, S, M', 'Instantaneous', 'Create or destroy up to 10 gallons of water, or call a brief downpour.'],
  ['Cure Wounds', 1, 'V', 'bcdpr', '1 action', 'Touch', 'V, S', 'Instantaneous', 'A creature you touch regains 1d8 + your spellcasting modifier hit points.'],
  ['Detect Evil and Good', 1, 'D', 'cp', '1 action', 'Self', 'V, S', 'Concentration, up to 10 minutes', 'Sense aberrations, celestials, elementals, fey, fiends, and undead within 30 feet.'],
  ['Detect Magic', 1, 'D', 'bcdprsw', '1 action', 'Self', 'V, S', 'Concentration, up to 10 minutes', 'Sense the presence and school of magic within 30 feet.'],
  ['Detect Poison and Disease', 1, 'D', 'cdpr', '1 action', 'Self', 'V, S, M', 'Concentration, up to 10 minutes', 'Sense poisons, poisonous creatures, and diseases within 30 feet.'],
  ['Disguise Self', 1, 'I', 'bsw', '1 action', 'Self', 'V, S', '1 hour', 'Change your appearance, including clothing and equipment, until dispelled.'],
  ['Dissonant Whispers', 1, 'E', 'b', '1 action', '60 ft.', 'V', 'Instantaneous', 'A discordant melody; WIS save or 3d6 psychic damage and the target flees.'],
  ['Divine Favor', 1, 'V', 'p', '1 bonus action', 'Self', 'V, S', 'Concentration, up to 1 minute', 'Your weapon attacks deal an extra 1d4 radiant damage.'],
  ['Entangle', 1, 'C', 'd', '1 action', '90 ft.', 'V, S', 'Concentration, up to 1 minute', 'Grasping weeds fill a 20-foot square, restraining creatures that fail a STR save.'],
  ['Expeditious Retreat', 1, 'T', 'skw', '1 bonus action', 'Self', 'V, S', 'Concentration, up to 10 minutes', 'Take the Dash action as a bonus action on each of your turns.'],
  ['Faerie Fire', 1, 'V', 'bd', '1 action', '60 ft.', 'V', 'Concentration, up to 1 minute', 'Objects and creatures in a 20-foot cube are outlined in light; attacks against them have advantage.'],
  ['False Life', 1, 'N', 'sw', '1 action', 'Self', 'V, S, M', '1 hour', 'You gain 1d4 + 4 temporary hit points.'],
  ['Feather Fall', 1, 'T', 'bsw', '1 reaction', '60 ft.', 'V, M', '1 minute', 'Up to five falling creatures descend at 60 feet per round and take no falling damage.'],
  ['Find Familiar', 1, 'C', 'w', '1 hour', '10 ft.', 'V, S, M', 'Instantaneous', 'Summon a spirit that takes an animal form and serves as your familiar.'],
  ['Fog Cloud', 1, 'C', 'drsw', '1 action', '120 ft.', 'V, S', 'Concentration, up to 1 hour', 'A 20-foot-radius sphere of fog heavily obscures the area.'],
  ['Grease', 1, 'C', 'w', '1 action', '60 ft.', 'V, S, M', '1 minute', 'Slick grease covers a 10-foot square; DEX save or fall prone.'],
  ['Guiding Bolt', 1, 'V', 'c', '1 action', '120 ft.', 'V, S', '1 round', '4d6 radiant damage, and the next attack against the target has advantage.'],
  ['Healing Word', 1, 'V', 'bcd', '1 bonus action', '60 ft.', 'V', 'Instantaneous', 'A creature regains 1d4 + your spellcasting modifier hit points.'],
  ['Hellish Rebuke', 1, 'V', 'k', '1 reaction', '60 ft.', 'V, S', 'Instantaneous', 'Wreath your attacker in flames; DEX save or 2d10 fire damage.'],
  ['Heroism', 1, 'E', 'bp', '1 action', 'Touch', 'V, S', 'Concentration, up to 1 minute', 'The target is immune to fear and gains temporary hit points each turn.'],
  ['Hex', 1, 'E', 'k', '1 bonus action', '90 ft.', 'V, S, M', 'Concentration, up to 1 hour', 'Your attacks deal an extra 1d6 necrotic damage to the target, which has disadvantage on one ability.'],
  ['Hunter’s Mark', 1, 'D', 'r', '1 bonus action', '90 ft.', 'V', 'Concentration, up to 1 hour', 'Your weapon attacks deal an extra 1d6 damage to the marked target.'],
  ['Identify', 1, 'D', 'bw', '1 minute', 'Touch', 'V, S, M', 'Instantaneous', 'Learn an item’s properties, how to use them, and any spells affecting it.'],
  ['Illusory Script', 1, 'I', 'bkw', '1 minute', 'Touch', 'S, M', '10 days', 'Write on parchment so that only chosen creatures can read the true message.'],
  ['Inflict Wounds', 1, 'N', 'c', '1 action', 'Touch', 'V, S', 'Instantaneous', 'A melee spell attack deals 3d10 necrotic damage.'],
  ['Jump', 1, 'T', 'drsw', '1 action', 'Touch', 'V, S, M', '1 minute', 'The target’s jump distance is tripled.'],
  ['Longstrider', 1, 'T', 'bdrw', '1 action', 'Touch', 'V, S, M', '1 hour', 'The target’s speed increases by 10 feet.'],
  ['Mage Armor', 1, 'A', 'sw', '1 action', 'Touch', 'V, S, M', '8 hours', 'An unarmoured creature’s base AC becomes 13 + its Dexterity modifier.'],
  ['Magic Missile', 1, 'V', 'sw', '1 action', '120 ft.', 'V, S', 'Instantaneous', 'Three darts each deal 1d4 + 1 force damage and always hit.'],
  ['Protection from Evil and Good', 1, 'A', 'cpwk', '1 action', 'Touch', 'V, S, M', 'Concentration, up to 10 minutes', 'Aberrations, celestials, elementals, fey, fiends, and undead have disadvantage to hit the target.'],
  ['Purify Food and Drink', 1, 'T', 'cdp', '1 action', '10 ft.', 'V, S', 'Instantaneous', 'Remove poison and disease from food and drink in a 5-foot radius.'],
  ['Ray of Sickness', 1, 'N', 'sw', '1 action', '60 ft.', 'V, S', 'Instantaneous', '2d8 poison damage, and a CON save or the target is poisoned until your next turn.'],
  ['Sanctuary', 1, 'A', 'cp', '1 bonus action', '30 ft.', 'V, S, M', '1 minute', 'Attackers must make a WIS save or choose a new target.'],
  ['Shield', 1, 'A', 'sw', '1 reaction', 'Self', 'V, S', '1 round', '+5 AC until your next turn, including against the triggering attack, and immunity to magic missile.'],
  ['Shield of Faith', 1, 'A', 'cp', '1 bonus action', '60 ft.', 'V, S, M', 'Concentration, up to 10 minutes', 'A shimmering field grants the target +2 AC.'],
  ['Silent Image', 1, 'I', 'bsw', '1 action', '60 ft.', 'V, S, M', 'Concentration, up to 10 minutes', 'Create a purely visual illusion no larger than a 15-foot cube.'],
  ['Sleep', 1, 'E', 'bsw', '1 action', '90 ft.', 'V, S, M', '1 minute', 'Creatures totalling 5d8 hit points fall unconscious, weakest first.'],
  ['Speak with Animals', 1, 'D', 'bdr', '1 action', 'Self', 'V, S', '10 minutes', 'You can comprehend and verbally communicate with beasts.'],
  ['Tasha’s Hideous Laughter', 1, 'E', 'bw', '1 action', '30 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'A creature falls prone with laughter, incapacitated, on a failed WIS save.'],
  ['Tenser’s Floating Disk', 1, 'C', 'w', '1 action', '30 ft.', 'V, S, M', '1 hour', 'A disc of force carries up to 500 pounds and follows you.'],
  ['Thunderwave', 1, 'V', 'bdsw', '1 action', 'Self (15-ft. cube)', 'V, S', 'Instantaneous', 'A wave of thunder deals 2d8 damage and pushes creatures 10 feet on a failed CON save.'],
  ['Unseen Servant', 1, 'C', 'bkw', '1 action', '60 ft.', 'V, S, M', '1 hour', 'An invisible force performs simple tasks at your command.'],
  ['Witch Bolt', 1, 'V', 'skw', '1 action', '30 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'A beam deals 1d12 lightning damage, and 1d12 again each turn you maintain it.'],

  // ------------------------------------------------------------------ level 2
  ['Aid', 2, 'A', 'cp', '1 action', '30 ft.', 'V, S, M', '8 hours', 'Three creatures gain 5 hit points and 5 to their maximum.'],
  ['Alter Self', 2, 'T', 'sw', '1 action', 'Self', 'V, S', 'Concentration, up to 1 hour', 'Adapt to water, change your appearance, or grow natural weapons.'],
  ['Animal Messenger', 2, 'E', 'bdr', '1 action', '30 ft.', 'V, S, M', '24 hours', 'Send a Tiny beast to deliver a message up to 50 miles.'],
  ['Arcane Lock', 2, 'A', 'w', '1 action', 'Touch', 'V, S, M', 'Until dispelled', 'A door or container becomes locked to all but you and those you name.'],
  ['Augury', 2, 'D', 'c', '1 minute', 'Self', 'V, S, M', 'Instantaneous', 'Learn whether a course of action in the next 30 minutes brings weal or woe.'],
  ['Barkskin', 2, 'T', 'dr', '1 action', 'Touch', 'V, S, M', 'Concentration, up to 1 hour', 'The target’s AC cannot be lower than 16.'],
  ['Blindness/Deafness', 2, 'N', 'bcsw', '1 action', '30 ft.', 'V', '1 minute', 'A creature is blinded or deafened on a failed CON save.'],
  ['Blur', 2, 'I', 'sw', '1 action', 'Self', 'V', 'Concentration, up to 1 minute', 'Your form blurs; attackers have disadvantage unless they can see without sight.'],
  ['Branding Smite', 2, 'V', 'p', '1 bonus action', 'Self', 'V', 'Concentration, up to 1 minute', 'Your next weapon hit deals an extra 2d6 radiant damage and reveals invisible targets.'],
  ['Calm Emotions', 2, 'E', 'bc', '1 action', '60 ft.', 'V, S', 'Concentration, up to 1 minute', 'Suppress charm and fear, or make hostile creatures indifferent.'],
  ['Continual Flame', 2, 'V', 'cw', '1 action', 'Touch', 'V, S, M', 'Until dispelled', 'A heatless flame burns on an object forever.'],
  ['Crown of Madness', 2, 'E', 'bskw', '1 action', '120 ft.', 'V, S', 'Concentration, up to 1 minute', 'A charmed humanoid must attack a creature of your choice each turn.'],
  ['Darkness', 2, 'V', 'skw', '1 action', '60 ft.', 'V, M', 'Concentration, up to 10 minutes', 'Magical darkness fills a 15-foot radius; even darkvision cannot see through it.'],
  ['Darkvision', 2, 'T', 'drsw', '1 action', 'Touch', 'V, S, M', '8 hours', 'The target gains darkvision out to 60 feet.'],
  ['Detect Thoughts', 2, 'D', 'bsw', '1 action', 'Self', 'V, S, M', 'Concentration, up to 1 minute', 'Read a creature’s surface thoughts, and probe deeper if it fails a WIS save.'],
  ['Enhance Ability', 2, 'T', 'bcds', '1 action', 'Touch', 'V, S, M', 'Concentration, up to 1 hour', 'The target gains advantage on checks with one ability, plus a bonus effect.'],
  ['Enlarge/Reduce', 2, 'T', 'sw', '1 action', '30 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'Double or halve a creature’s size, adjusting damage and Strength checks.'],
  ['Enthrall', 2, 'E', 'bk', '1 action', '60 ft.', 'V, S', '1 minute', 'Creatures have disadvantage on Perception checks to notice anything but you.'],
  ['Find Steed', 2, 'C', 'p', '10 minutes', '30 ft.', 'V, S', 'Instantaneous', 'Summon a loyal spirit steed that shares your saving throws while nearby.'],
  ['Find Traps', 2, 'D', 'cdr', '1 action', '120 ft.', 'V, S', 'Instantaneous', 'Sense the presence of any magical trap within range.'],
  ['Flame Blade', 2, 'V', 'd', '1 bonus action', 'Self', 'V, S, M', 'Concentration, up to 10 minutes', 'A fiery scimitar deals 3d6 fire damage on a hit and sheds light.'],
  ['Flaming Sphere', 2, 'C', 'dw', '1 action', '60 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'A 5-foot sphere of fire you can move 30 feet each turn deals 2d6 fire damage.'],
  ['Gentle Repose', 2, 'N', 'cw', '1 action', 'Touch', 'V, S, M', '10 days', 'A corpse is protected from decay and cannot become undead.'],
  ['Gust of Wind', 2, 'V', 'dsw', '1 action', 'Self (60-ft. line)', 'V, S, M', 'Concentration, up to 1 minute', 'A blast of wind pushes creatures 15 feet and makes the line difficult terrain.'],
  ['Heat Metal', 2, 'T', 'bd', '1 action', '60 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'A metal object glows; 2d8 fire damage to whoever holds it, and it may be dropped.'],
  ['Hold Person', 2, 'E', 'bcdskw', '1 action', '60 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'A humanoid is paralysed while it keeps failing WIS saves.'],
  ['Invisibility', 2, 'I', 'bskw', '1 action', 'Touch', 'V, S, M', 'Concentration, up to 1 hour', 'The target is invisible until it attacks or casts a spell.'],
  ['Knock', 2, 'T', 'bsw', '1 action', '60 ft.', 'V', 'Instantaneous', 'Loudly unlock a door, chest, or shackle, suppressing arcane lock for 10 minutes.'],
  ['Lesser Restoration', 2, 'A', 'bcdpr', '1 action', 'Touch', 'V, S', 'Instantaneous', 'End one disease or the blinded, deafened, paralysed, or poisoned condition.'],
  ['Levitate', 2, 'T', 'sw', '1 action', '60 ft.', 'V, S, M', 'Concentration, up to 10 minutes', 'A creature or object rises up to 20 feet and can be moved vertically.'],
  ['Locate Animals or Plants', 2, 'D', 'bdr', '1 action', 'Self', 'V, S, M', 'Instantaneous', 'Learn the direction and distance to the nearest specimen within 5 miles.'],
  ['Locate Object', 2, 'D', 'bcdprw', '1 action', 'Self', 'V, S, M', 'Concentration, up to 10 minutes', 'Sense the direction to a familiar object within 1,000 feet.'],
  ['Magic Mouth', 2, 'I', 'bw', '1 minute', '30 ft.', 'V, S, M', 'Until dispelled', 'An object speaks a message you set when a trigger occurs.'],
  ['Magic Weapon', 2, 'T', 'pw', '1 bonus action', 'Touch', 'V, S', 'Concentration, up to 1 hour', 'A weapon becomes magical with a +1 bonus to attack and damage.'],
  ['Mirror Image', 2, 'I', 'skw', '1 action', 'Self', 'V, S', '1 minute', 'Three illusory duplicates may absorb attacks aimed at you.'],
  ['Misty Step', 2, 'C', 'skw', '1 bonus action', 'Self', 'V', 'Instantaneous', 'Teleport up to 30 feet to an unoccupied space you can see.'],
  ['Moonbeam', 2, 'V', 'd', '1 action', '120 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'A 5-foot beam of moonlight deals 2d10 radiant damage and reverts shapechangers.'],
  ['Nystul’s Magic Aura', 2, 'I', 'w', '1 action', 'Touch', 'V, S, M', '24 hours', 'Mask a creature or object from divination, or give it a false aura.'],
  ['Pass without Trace', 2, 'A', 'dr', '1 action', 'Self', 'V, S, M', 'Concentration, up to 1 hour', 'You and nearby allies gain +10 to Stealth and leave no tracks.'],
  ['Prayer of Healing', 2, 'V', 'c', '10 minutes', '30 ft.', 'V', 'Instantaneous', 'Up to six creatures each regain 2d8 + your spellcasting modifier hit points.'],
  ['Protection from Poison', 2, 'A', 'cdpr', '1 action', 'Touch', 'V, S', '1 hour', 'Neutralise one poison and grant advantage on saves against poison.'],
  ['Ray of Enfeeblement', 2, 'N', 'kw', '1 action', '60 ft.', 'V, S', 'Concentration, up to 1 minute', 'The target deals half damage with Strength-based weapon attacks.'],
  ['Rope Trick', 2, 'T', 'w', '1 action', 'Touch', 'V, S, M', '1 hour', 'A rope leads to an extradimensional space holding up to eight creatures.'],
  ['Scorching Ray', 2, 'V', 'sw', '1 action', '120 ft.', 'V, S', 'Instantaneous', 'Three rays of fire each deal 2d6 fire damage on a hit.'],
  ['See Invisibility', 2, 'D', 'bsw', '1 action', 'Self', 'V, S, M', '1 hour', 'You see invisible creatures and objects, and into the Ethereal Plane.'],
  ['Shatter', 2, 'V', 'bskw', '1 action', '60 ft.', 'V, S, M', 'Instantaneous', 'A ringing burst deals 3d8 thunder damage in a 10-foot radius.'],
  ['Silence', 2, 'I', 'bcr', '1 action', '120 ft.', 'V, S', 'Concentration, up to 10 minutes', 'No sound can be created or pass within a 20-foot radius sphere.'],
  ['Spider Climb', 2, 'T', 'skw', '1 action', 'Touch', 'V, S, M', 'Concentration, up to 1 hour', 'The target can walk on walls and ceilings with its hands free.'],
  ['Spike Growth', 2, 'T', 'dr', '1 action', '150 ft.', 'V, S, M', 'Concentration, up to 10 minutes', 'A 20-foot radius becomes difficult terrain dealing 2d4 piercing damage per 5 feet moved.'],
  ['Spiritual Weapon', 2, 'V', 'c', '1 bonus action', '60 ft.', 'V, S', '1 minute', 'A floating weapon attacks for 1d8 + your spellcasting modifier force damage.'],
  ['Suggestion', 2, 'E', 'bskw', '1 action', '30 ft.', 'V, M', 'Concentration, up to 8 hours', 'Suggest a reasonable course of action the target must pursue on a failed WIS save.'],
  ['Warding Bond', 2, 'A', 'c', '1 action', 'Touch', 'V, S, M', '1 hour', 'The target gains +1 AC and saves and resistance, but you take the damage it takes.'],
  ['Web', 2, 'C', 'sw', '1 action', '60 ft.', 'V, S, M', 'Concentration, up to 1 hour', 'Thick webs fill a 20-foot cube, restraining creatures that fail a DEX save.'],
  ['Zone of Truth', 2, 'E', 'bcp', '1 action', '60 ft.', 'V, S', '10 minutes', 'Creatures in a 15-foot radius cannot speak a deliberate lie.'],

  // ------------------------------------------------------------------ level 3
  ['Animate Dead', 3, 'N', 'cw', '1 minute', '10 ft.', 'V, S, M', 'Instantaneous', 'Raise a skeleton or zombie from a corpse to obey your commands.'],
  ['Beacon of Hope', 3, 'A', 'c', '1 action', '30 ft.', 'V, S', 'Concentration, up to 1 minute', 'Creatures gain advantage on WIS and death saves and regain maximum hit points from healing.'],
  ['Bestow Curse', 3, 'N', 'bcw', '1 action', 'Touch', 'V, S', 'Concentration, up to 1 minute', 'Curse a creature with disadvantage, wasted turns, or extra necrotic damage.'],
  ['Blink', 3, 'T', 'sw', '1 action', 'Self', 'V, S', '1 minute', 'Each turn, a d20 roll may send you to the Ethereal Plane and back.'],
  ['Call Lightning', 3, 'C', 'd', '1 action', '120 ft.', 'V, S', 'Concentration, up to 10 minutes', 'A storm cloud drops a bolt for 3d10 lightning damage each turn.'],
  ['Clairvoyance', 3, 'D', 'bcsw', '10 minutes', '1 mile', 'V, S, M', 'Concentration, up to 10 minutes', 'Create an invisible sensor to see or hear a distant place.'],
  ['Conjure Animals', 3, 'C', 'dr', '1 action', '60 ft.', 'V, S', 'Concentration, up to 1 hour', 'Summon fey spirits in beast form that fight for you.'],
  ['Counterspell', 3, 'A', 'skw', '1 reaction', '60 ft.', 'S', 'Instantaneous', 'Interrupt a creature casting a spell; 3rd level or lower fails automatically.'],
  ['Create Food and Water', 3, 'C', 'cp', '1 action', '30 ft.', 'V, S', 'Instantaneous', 'Produce 45 pounds of food and 30 gallons of water.'],
  ['Daylight', 3, 'V', 'cdprs', '1 action', '60 ft.', 'V, S', '1 hour', 'A 60-foot radius of bright sunlight, which dispels weaker darkness.'],
  ['Dispel Magic', 3, 'A', 'bcdpskw', '1 action', '120 ft.', 'V, S', 'Instantaneous', 'End spells of 3rd level or lower on a target, or make a check for higher ones.'],
  ['Fear', 3, 'I', 'bskw', '1 action', 'Self (30-ft. cone)', 'V, S, M', 'Concentration, up to 1 minute', 'Creatures drop what they hold and flee on a failed WIS save.'],
  ['Feign Death', 3, 'N', 'bcdw', '1 action', 'Touch', 'V, S, M', '1 hour', 'A willing creature appears dead and gains resistance to all but psychic damage.'],
  ['Fireball', 3, 'V', 'sw', '1 action', '150 ft.', 'V, S, M', 'Instantaneous', 'A 20-foot radius explosion deals 8d6 fire damage, half on a DEX save.'],
  ['Fly', 3, 'T', 'skw', '1 action', 'Touch', 'V, S, M', 'Concentration, up to 10 minutes', 'The target gains a flying speed of 60 feet.'],
  ['Gaseous Form', 3, 'T', 'skw', '1 action', 'Touch', 'V, S, M', 'Concentration, up to 1 hour', 'A creature becomes a misty cloud with a flying speed and resistance to weapons.'],
  ['Glyph of Warding', 3, 'A', 'bcw', '1 hour', 'Touch', 'V, S, M', 'Until dispelled', 'Inscribe a glyph that discharges a spell or 5d8 damage when triggered.'],
  ['Haste', 3, 'T', 'sw', '1 action', '30 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'Double speed, +2 AC, advantage on DEX saves, and an extra limited action each turn.'],
  ['Hypnotic Pattern', 3, 'I', 'bskw', '1 action', '120 ft.', 'S, M', 'Concentration, up to 1 minute', 'A twisting pattern charms and incapacitates creatures in a 30-foot cube.'],
  ['Lightning Bolt', 3, 'V', 'sw', '1 action', 'Self (100-ft. line)', 'V, S, M', 'Instantaneous', 'A stroke of lightning deals 8d6 damage, half on a DEX save.'],
  ['Magic Circle', 3, 'A', 'ckpw', '1 minute', '10 ft.', 'V, S, M', '1 hour', 'A cylinder that keeps out — or traps — a chosen type of creature.'],
  ['Major Image', 3, 'I', 'bskw', '1 action', '120 ft.', 'V, S, M', 'Concentration, up to 10 minutes', 'A detailed illusion with sound, smell, and temperature, no larger than a 20-foot cube.'],
  ['Mass Healing Word', 3, 'V', 'c', '1 bonus action', '60 ft.', 'V', 'Instantaneous', 'Up to six creatures regain 1d4 + your spellcasting modifier hit points.'],
  ['Meld into Stone', 3, 'T', 'cd', '1 action', 'Touch', 'V, S', '8 hours', 'Step into a stone object large enough to contain you.'],
  ['Nondetection', 3, 'A', 'brw', '1 action', 'Touch', 'V, S, M', '8 hours', 'Hide a target from divination magic and scrying sensors.'],
  ['Phantom Steed', 3, 'I', 'w', '1 minute', '30 ft.', 'V, S', '1 hour', 'A quasi-real horse with a speed of 100 feet carries a rider.'],
  ['Plant Growth', 3, 'T', 'bdr', '1 action or 8 hours', '150 ft.', 'V, S', 'Instantaneous', 'Overgrow an area into difficult terrain, or enrich half a mile of land.'],
  ['Protection from Energy', 3, 'A', 'cdrsw', '1 action', 'Touch', 'V, S', 'Concentration, up to 1 hour', 'Resistance to one of acid, cold, fire, lightning, or thunder damage.'],
  ['Remove Curse', 3, 'A', 'ckpw', '1 action', 'Touch', 'V, S', 'Instantaneous', 'End all curses on a creature or break an item’s attunement curse.'],
  ['Revivify', 3, 'N', 'cp', '1 action', 'Touch', 'V, S, M', 'Instantaneous', 'Return a creature dead no longer than a minute to life with 1 hit point.'],
  ['Sending', 3, 'V', 'bcw', '1 action', 'Unlimited', 'V, S, M', '1 round', 'Send a 25-word message to a creature you know anywhere, and receive a brief reply.'],
  ['Sleet Storm', 3, 'C', 'dsw', '1 action', '150 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'Freezing rain douses flames, obscures vision, and knocks creatures prone.'],
  ['Slow', 3, 'T', 'sw', '1 action', '120 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'Up to six creatures have halved speed, -2 AC and DEX saves, and one action fewer.'],
  ['Speak with Dead', 3, 'N', 'bc', '1 action', '10 ft.', 'V, S, M', '10 minutes', 'Ask a corpse five questions; it answers cryptically and knows only what it knew in life.'],
  ['Speak with Plants', 3, 'T', 'bdr', '1 action', 'Self (30-ft. radius)', 'V, S', '10 minutes', 'Question plants, and command them to move or free a path.'],
  ['Spirit Guardians', 3, 'C', 'c', '1 action', 'Self (15-ft. radius)', 'V, S, M', 'Concentration, up to 10 minutes', 'Spirits deal 3d8 radiant or necrotic damage and halve the speed of enemies nearby.'],
  ['Stinking Cloud', 3, 'C', 'bskw', '1 action', '90 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'A nauseating gas makes creatures waste their action retching.'],
  ['Tongues', 3, 'D', 'bcskw', '1 action', 'Touch', 'V, M', '1 hour', 'The target understands and is understood in any spoken language.'],
  ['Vampiric Touch', 3, 'N', 'kw', '1 action', 'Self', 'V, S', 'Concentration, up to 1 minute', 'A melee spell attack deals 3d6 necrotic damage and heals you for half.'],
  ['Water Breathing', 3, 'T', 'drsw', '1 action', '30 ft.', 'V, S, M', '24 hours', 'Up to ten creatures can breathe underwater.'],
  ['Water Walk', 3, 'T', 'cdrs', '1 action', '30 ft.', 'V, S, M', '1 hour', 'Up to ten creatures can move across any liquid as if it were solid ground.'],
  ['Wind Wall', 3, 'V', 'dr', '1 action', '120 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'A wall of strong wind deals 3d8 bludgeoning damage and deflects arrows.'],

  // ------------------------------------------------------------------ level 4
  ['Arcane Eye', 4, 'D', 'w', '1 action', '30 ft.', 'V, S, M', 'Concentration, up to 1 hour', 'An invisible eye with darkvision flies where you direct it.'],
  ['Banishment', 4, 'A', 'ckpsw', '1 action', '60 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'Send a creature to a harmless demiplane, or back to its home plane permanently.'],
  ['Blight', 4, 'N', 'dskw', '1 action', '30 ft.', 'V, S', 'Instantaneous', 'Drain moisture for 8d8 necrotic damage; plants automatically fail the save.'],
  ['Compulsion', 4, 'E', 'b', '1 action', '30 ft.', 'V, S', 'Concentration, up to 1 minute', 'Creatures must move in a direction you choose on their turns.'],
  ['Confusion', 4, 'E', 'bdsw', '1 action', '90 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'Creatures in a 10-foot radius act randomly on a failed WIS save.'],
  ['Conjure Minor Elementals', 4, 'C', 'dw', '1 minute', '90 ft.', 'V, S', 'Concentration, up to 1 hour', 'Summon elemental spirits that obey your commands.'],
  ['Conjure Woodland Beings', 4, 'C', 'dr', '1 action', '60 ft.', 'V, S, M', 'Concentration, up to 1 hour', 'Summon fey creatures that fight alongside you.'],
  ['Control Water', 4, 'T', 'cdw', '1 action', '300 ft.', 'V, S, M', 'Concentration, up to 10 minutes', 'Raise a flood, part water, redirect a current, or create a whirlpool.'],
  ['Death Ward', 4, 'A', 'cp', '1 action', 'Touch', 'V, S', '8 hours', 'The first time the target would drop to 0 hit points, it drops to 1 instead.'],
  ['Dimension Door', 4, 'C', 'bskw', '1 action', '500 ft.', 'V', 'Instantaneous', 'Teleport yourself and one willing creature to a place you can picture.'],
  ['Divination', 4, 'D', 'c', '1 action', 'Self', 'V, S, M', 'Instantaneous', 'Receive a short, truthful answer about a goal or event within a week.'],
  ['Dominate Beast', 4, 'E', 'ds', '1 action', '60 ft.', 'V, S', 'Concentration, up to 1 minute', 'Charm a beast and issue it commands telepathically.'],
  ['Fabricate', 4, 'T', 'w', '10 minutes', '120 ft.', 'V, S', 'Instantaneous', 'Convert raw material into a finished product of the same substance.'],
  ['Faithful Hound', 4, 'C', 'w', '1 action', '30 ft.', 'V, S, M', '8 hours', 'An invisible watchdog barks at intruders and bites for 4d8 piercing damage.'],
  ['Fire Shield', 4, 'V', 'w', '1 action', 'Self', 'V, S, M', '10 minutes', 'Flames grant resistance to cold or fire and burn attackers for 2d8 damage.'],
  ['Freedom of Movement', 4, 'A', 'bcdr', '1 action', 'Touch', 'V, S, M', '1 hour', 'The target ignores difficult terrain and cannot be paralysed or restrained.'],
  ['Giant Insect', 4, 'T', 'd', '1 action', '30 ft.', 'V, S', 'Concentration, up to 10 minutes', 'Enlarge insects into giant versions that obey you.'],
  ['Greater Invisibility', 4, 'I', 'bsw', '1 action', 'Touch', 'V, S', 'Concentration, up to 1 minute', 'The target is invisible even while attacking and casting.'],
  ['Guardian of Faith', 4, 'C', 'c', '1 action', '30 ft.', 'V', '8 hours', 'A spectral guardian deals 20 radiant damage to hostile creatures that come near.'],
  ['Hallucinatory Terrain', 4, 'I', 'bdkw', '10 minutes', '300 ft.', 'V, S, M', '24 hours', 'Disguise natural terrain across a 150-foot cube.'],
  ['Ice Storm', 4, 'V', 'dsw', '1 action', '300 ft.', 'V, S, M', 'Instantaneous', 'Hail deals 2d8 bludgeoning and 4d6 cold damage and leaves difficult terrain.'],
  ['Locate Creature', 4, 'D', 'bcdprw', '1 action', 'Self', 'V, S, M', 'Concentration, up to 1 hour', 'Sense the direction to a creature you know within 1,000 feet.'],
  ['Phantasmal Killer', 4, 'I', 'w', '1 action', '120 ft.', 'V, S', 'Concentration, up to 1 minute', 'A nightmare visible only to the target deals 4d10 psychic damage each turn.'],
  ['Polymorph', 4, 'T', 'bdsw', '1 action', '60 ft.', 'V, S, M', 'Concentration, up to 1 hour', 'Transform a creature into a beast of equal or lower challenge rating.'],
  ['Private Sanctum', 4, 'A', 'w', '10 minutes', '120 ft.', 'V, S, M', '24 hours', 'Ward an area against sound, sight, divination, and teleportation.'],
  ['Resilient Sphere', 4, 'V', 'w', '1 action', '30 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'An impervious sphere of force encloses a creature or object.'],
  ['Secret Chest', 4, 'C', 'w', '1 action', 'Touch', 'V, S, M', 'Instantaneous', 'Hide a chest on the Ethereal Plane and recall it at will.'],
  ['Stone Shape', 4, 'T', 'cdw', '1 action', 'Touch', 'V, S, M', 'Instantaneous', 'Reshape a Medium-or-smaller section of stone into any form.'],
  ['Stoneskin', 4, 'A', 'drsw', '1 action', 'Touch', 'V, S, M', 'Concentration, up to 1 hour', 'The target has resistance to nonmagical bludgeoning, piercing, and slashing damage.'],
  ['Wall of Fire', 4, 'V', 'dsw', '1 action', '120 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'A wall of flame deals 5d8 fire damage to creatures on the side you choose.'],

  // ------------------------------------------------------------------ level 5
  ['Animate Objects', 5, 'T', 'bsw', '1 action', '120 ft.', 'V, S', 'Concentration, up to 1 minute', 'Up to ten objects come to life and attack at your command.'],
  ['Antilife Shell', 5, 'A', 'd', '1 action', 'Self (10-ft. radius)', 'V, S', 'Concentration, up to 1 hour', 'A barrier prevents living creatures from entering.'],
  ['Awaken', 5, 'T', 'bd', '8 hours', 'Touch', 'V, S, M', 'Instantaneous', 'Give a beast or plant sentience, speech, and loyalty to you.'],
  ['Bigby’s Hand', 5, 'V', 'w', '1 action', '120 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'A Large hand of force punches, grapples, pushes, or shields.'],
  ['Cloudkill', 5, 'C', 'sw', '1 action', '120 ft.', 'V, S', 'Concentration, up to 10 minutes', 'A moving fog of poison deals 5d8 poison damage each turn.'],
  ['Commune', 5, 'D', 'c', '1 minute', 'Self', 'V, S, M', '1 minute', 'Ask your deity three yes-or-no questions.'],
  ['Commune with Nature', 5, 'D', 'dr', '1 minute', 'Self', 'V, S', 'Instantaneous', 'Learn three facts about the terrain within three miles.'],
  ['Cone of Cold', 5, 'V', 'sw', '1 action', 'Self (60-ft. cone)', 'V, S, M', 'Instantaneous', 'A blast of cold deals 8d8 cold damage, half on a CON save.'],
  ['Conjure Elemental', 5, 'C', 'dw', '1 minute', '90 ft.', 'V, S, M', 'Concentration, up to 1 hour', 'Summon an elemental that obeys you while you concentrate.'],
  ['Contact Other Plane', 5, 'D', 'kw', '1 minute', 'Self', 'V', '1 minute', 'Question an extraplanar intelligence at the risk of your own sanity.'],
  ['Contagion', 5, 'N', 'cd', '1 action', 'Touch', 'V, S', '7 days', 'Inflict a debilitating disease with a melee spell attack.'],
  ['Creation', 5, 'I', 'sw', '1 minute', '30 ft.', 'V, S, M', 'Special', 'Pull matter from the Shadowfell to create a temporary object.'],
  ['Dispel Evil and Good', 5, 'A', 'cp', '1 action', 'Self', 'V, S, M', 'Concentration, up to 1 minute', 'Extraplanar creatures have disadvantage against you, and you can break their hold.'],
  ['Dominate Person', 5, 'E', 'bsw', '1 action', '60 ft.', 'V, S', 'Concentration, up to 1 minute', 'Charm a humanoid and command it telepathically.'],
  ['Dream', 5, 'I', 'bkw', '1 minute', 'Special', 'V, S, M', '8 hours', 'Shape a sleeping creature’s dreams, and deliver a message or a nightmare.'],
  ['Flame Strike', 5, 'V', 'c', '1 action', '60 ft.', 'V, S, M', 'Instantaneous', 'A column of fire deals 4d6 fire and 4d6 radiant damage.'],
  ['Geas', 5, 'E', 'bcdpw', '1 minute', '60 ft.', 'V', '30 days', 'Command a creature to a course of action; disobeying deals 5d10 psychic damage.'],
  ['Greater Restoration', 5, 'A', 'bcdr', '1 action', 'Touch', 'V, S, M', 'Instantaneous', 'End a charm, petrification, curse, ability reduction, or hit point maximum reduction.'],
  ['Hallow', 5, 'V', 'c', '24 hours', 'Touch', 'V, S, M', 'Until dispelled', 'Imbue an area with a warding effect and an extra magical property.'],
  ['Hold Monster', 5, 'E', 'bskw', '1 action', '90 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'Paralyse a creature that is not undead while it keeps failing WIS saves.'],
  ['Insect Plague', 5, 'C', 'cds', '1 action', '300 ft.', 'V, S, M', 'Concentration, up to 10 minutes', 'A swarm of locusts fills a 20-foot sphere for 4d10 piercing damage.'],
  ['Legend Lore', 5, 'D', 'bcw', '10 minutes', 'Self', 'V, S, M', 'Instantaneous', 'Learn significant lore about a person, place, or object.'],
  ['Mass Cure Wounds', 5, 'V', 'bcd', '1 action', '60 ft.', 'V, S', 'Instantaneous', 'Up to six creatures each regain 3d8 + your spellcasting modifier hit points.'],
  ['Mislead', 5, 'I', 'bw', '1 action', 'Self', 'S', 'Concentration, up to 1 hour', 'You turn invisible while an illusory double acts in your place.'],
  ['Modify Memory', 5, 'E', 'bw', '1 action', '30 ft.', 'V, S', 'Concentration, up to 1 minute', 'Reshape a creature’s memory of an event in the last 24 hours.'],
  ['Passwall', 5, 'T', 'w', '1 action', '30 ft.', 'V, S, M', '1 hour', 'Open a passage through wood, plaster, or stone.'],
  ['Planar Binding', 5, 'A', 'bcdw', '1 hour', '60 ft.', 'V, S, M', '24 hours', 'Bind a celestial, elemental, fey, or fiend to your service.'],
  ['Raise Dead', 5, 'N', 'bcp', '1 hour', 'Touch', 'V, S, M', 'Instantaneous', 'Return a creature dead up to 10 days to life with 1 hit point.'],
  ['Reincarnate', 5, 'T', 'd', '1 hour', 'Touch', 'V, S, M', 'Instantaneous', 'Return a dead humanoid to life in a new randomly determined body.'],
  ['Scrying', 5, 'D', 'bcdw', '10 minutes', 'Self', 'V, S, M', 'Concentration, up to 10 minutes', 'See and hear a creature anywhere on the same plane through a sensor.'],
  ['Seeming', 5, 'I', 'bsw', '1 action', '30 ft.', 'V, S', '8 hours', 'Change the appearance of any number of creatures you can see.'],
  ['Telekinesis', 5, 'T', 'sw', '1 action', '60 ft.', 'V, S', 'Concentration, up to 10 minutes', 'Move a creature or a 1,000-pound object with your mind.'],
  ['Teleportation Circle', 5, 'C', 'bsw', '1 minute', '10 ft.', 'V, M', '1 round', 'Open a portal to a permanent teleportation circle you know.'],
  ['Tree Stride', 5, 'C', 'dr', '1 action', 'Self', 'V, S', 'Concentration, up to 1 minute', 'Step into one tree and out of another of the same kind up to 500 feet away.'],
  ['Wall of Force', 5, 'V', 'w', '1 action', '120 ft.', 'V, S, M', 'Concentration, up to 10 minutes', 'An invisible wall nothing can pass through physically.'],
  ['Wall of Stone', 5, 'V', 'dsw', '1 action', '120 ft.', 'V, S, M', 'Concentration, up to 10 minutes', 'A stone wall you can shape, which becomes permanent if maintained.'],

  // ------------------------------------------------------------------ level 6
  ['Blade Barrier', 6, 'V', 'c', '1 action', '90 ft.', 'V, S', 'Concentration, up to 10 minutes', 'A wall of whirling blades deals 6d10 slashing damage.'],
  ['Chain Lightning', 6, 'V', 'sw', '1 action', '150 ft.', 'V, S, M', 'Instantaneous', '10d8 lightning damage that arcs to three additional targets.'],
  ['Circle of Death', 6, 'N', 'skw', '1 action', '150 ft.', 'V, S, M', 'Instantaneous', 'A sphere of negative energy deals 8d6 necrotic damage in a 60-foot radius.'],
  ['Conjure Fey', 6, 'C', 'dk', '1 minute', '90 ft.', 'V, S', 'Concentration, up to 1 hour', 'Summon a fey creature of challenge rating 6 or lower.'],
  ['Contingency', 6, 'V', 'w', '10 minutes', 'Self', 'V, S, M', '10 days', 'Store a spell that triggers automatically under a circumstance you set.'],
  ['Create Undead', 6, 'N', 'ckw', '1 minute', '10 ft.', 'V, S, M', 'Instantaneous', 'Create up to three ghouls that obey your commands.'],
  ['Disintegrate', 6, 'T', 'sw', '1 action', '60 ft.', 'V, S, M', 'Instantaneous', '10d6 + 40 force damage; a creature reduced to 0 hit points crumbles to dust.'],
  ['Eyebite', 6, 'N', 'bskw', '1 action', 'Self', 'V, S', 'Concentration, up to 1 minute', 'Your gaze puts creatures to sleep, panics them, or sickens them each turn.'],
  ['Find the Path', 6, 'D', 'bcd', '1 minute', 'Self', 'V, S, M', 'Concentration, up to 1 day', 'Know the shortest route to a location you are familiar with.'],
  ['Flesh to Stone', 6, 'T', 'kw', '1 action', '60 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'Turn a creature to stone as it keeps failing CON saves.'],
  ['Forbiddance', 6, 'A', 'c', '10 minutes', 'Touch', 'V, S, M', '1 day', 'Ward an area against teleportation and damage a chosen creature type.'],
  ['Globe of Invulnerability', 6, 'A', 'sw', '1 action', 'Self (10-ft. radius)', 'V, S, M', 'Concentration, up to 1 minute', 'Spells of 5th level and lower cannot affect anything inside.'],
  ['Guards and Wards', 6, 'A', 'bw', '10 minutes', 'Touch', 'V, S, M', '24 hours', 'A suite of magical defences protects a structure.'],
  ['Harm', 6, 'N', 'c', '1 action', '60 ft.', 'V, S', 'Instantaneous', '14d6 necrotic damage, and the target’s hit point maximum is reduced to match.'],
  ['Heal', 6, 'V', 'cd', '1 action', '60 ft.', 'V, S', 'Instantaneous', 'Restore 70 hit points and end blindness, deafness, and disease.'],
  ['Heroes’ Feast', 6, 'C', 'cd', '10 minutes', '30 ft.', 'V, S, M', 'Instantaneous', 'A feast cures disease and poison and grants extra hit points for 24 hours.'],
  ['Instant Summons', 6, 'C', 'w', '1 minute', 'Touch', 'V, S, M', 'Until dispelled', 'Summon a marked object to your hand from any distance.'],
  ['Irresistible Dance', 6, 'E', 'bw', '1 action', '30 ft.', 'V', 'Concentration, up to 1 minute', 'A creature dances comically with disadvantage on attacks and DEX saves.'],
  ['Magic Jar', 6, 'N', 'w', '1 minute', 'Self', 'V, S, M', 'Until dispelled', 'Move your soul into a container and then into other bodies.'],
  ['Mass Suggestion', 6, 'E', 'bskw', '1 action', '60 ft.', 'V, M', '24 hours', 'Suggest a course of action to up to twelve creatures at once.'],
  ['Move Earth', 6, 'T', 'dsw', '1 action', '120 ft.', 'V, S, M', 'Concentration, up to 2 hours', 'Reshape the terrain across a 40-foot square.'],
  ['Planar Ally', 6, 'C', 'c', '10 minutes', '60 ft.', 'V, S', 'Instantaneous', 'Call on a celestial, elemental, or fiend, which bargains for its services.'],
  ['Programmed Illusion', 6, 'I', 'bw', '1 action', '120 ft.', 'V, S, M', 'Until dispelled', 'An illusion that plays when a condition you set is met.'],
  ['Sunbeam', 6, 'V', 'dsw', '1 action', 'Self (60-ft. line)', 'V, S, M', 'Concentration, up to 1 minute', 'A beam of sunlight deals 6d8 radiant damage and blinds; usable each turn.'],
  ['True Seeing', 6, 'D', 'bcskw', '1 action', 'Touch', 'V, S, M', '1 hour', 'See through illusions, invisibility, and shapechanging out to 120 feet.'],
  ['Wall of Ice', 6, 'V', 'w', '1 action', '120 ft.', 'V, S, M', 'Concentration, up to 10 minutes', 'A wall of ice blocks movement and deals cold damage to those breaking through.'],
  ['Wall of Thorns', 6, 'C', 'd', '1 action', '120 ft.', 'V, S, M', 'Concentration, up to 10 minutes', 'A thicket of thorns deals 7d8 piercing damage to creatures that enter.'],
  ['Wind Walk', 6, 'T', 'd', '1 minute', '30 ft.', 'V, S, M', '8 hours', 'You and your companions become clouds and fly at 300 feet per round.'],
  ['Word of Recall', 6, 'C', 'c', '1 action', '5 ft.', 'V', 'Instantaneous', 'Teleport yourself and up to five companions to a sanctuary you designated.'],

  // ------------------------------------------------------------------ level 7
  ['Arcane Sword', 7, 'V', 'bw', '1 action', '60 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'A sword of force attacks for 3d10 force damage each turn.'],
  ['Conjure Celestial', 7, 'C', 'c', '1 minute', '90 ft.', 'V, S', 'Concentration, up to 1 hour', 'Summon a celestial of challenge rating 4 or lower.'],
  ['Delayed Blast Fireball', 7, 'V', 'sw', '1 action', '150 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'A bead of fire grows more damaging each round until it detonates.'],
  ['Etherealness', 7, 'T', 'bcskw', '1 action', 'Self', 'V, S', 'Up to 8 hours', 'Step into the Ethereal Plane and move through solid objects.'],
  ['Finger of Death', 7, 'N', 'skw', '1 action', '60 ft.', 'V, S', 'Instantaneous', '7d8 + 30 necrotic damage; a humanoid killed rises as a zombie under your control.'],
  ['Fire Storm', 7, 'V', 'cds', '1 action', '150 ft.', 'V, S', 'Instantaneous', 'Roaring flame deals 7d10 fire damage across ten 10-foot cubes.'],
  ['Forcecage', 7, 'V', 'bkw', '1 action', '100 ft.', 'V, S, M', '1 hour', 'An inescapable cage or box of force traps everything inside.'],
  ['Magnificent Mansion', 7, 'C', 'bw', '1 minute', '300 ft.', 'V, S, M', '24 hours', 'Create an extradimensional dwelling with servants and a banquet.'],
  ['Mirage Arcane', 7, 'I', 'bdw', '10 minutes', 'Sight', 'V, S', '10 days', 'Make terrain look, sound, and feel like something else for a mile.'],
  ['Plane Shift', 7, 'C', 'cdskw', '1 action', 'Touch', 'V, S, M', 'Instantaneous', 'Transport willing creatures to another plane, or banish an unwilling one.'],
  ['Prismatic Spray', 7, 'V', 'sw', '1 action', 'Self (60-ft. cone)', 'V, S', 'Instantaneous', 'Eight coloured rays with different damage types and effects.'],
  ['Project Image', 7, 'I', 'bw', '1 action', '500 miles', 'V, S, M', 'Concentration, up to 1 day', 'Create a duplicate of yourself you can see and speak through.'],
  ['Regenerate', 7, 'T', 'bcd', '1 minute', 'Touch', 'V, S, M', '1 hour', 'Restore 4d8 + 15 hit points, then 1 hit point per turn, and regrow limbs.'],
  ['Resurrection', 7, 'N', 'bc', '1 hour', 'Touch', 'V, S, M', 'Instantaneous', 'Return a creature dead up to a century to life with all its hit points.'],
  ['Reverse Gravity', 7, 'T', 'dsw', '1 action', '100 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'Gravity reverses in a 50-foot radius cylinder.'],
  ['Sequester', 7, 'T', 'w', '1 action', 'Touch', 'V, S, M', 'Until dispelled', 'Hide a creature or object in stasis, invisible to sight and divination.'],
  ['Simulacrum', 7, 'I', 'w', '12 hours', 'Touch', 'V, S, M', 'Until dispelled', 'Create an obedient duplicate of a creature with half its hit points.'],
  ['Symbol', 7, 'A', 'bcw', '1 minute', 'Touch', 'V, S, M', 'Until dispelled', 'Inscribe a glyph that unleashes a harmful effect when triggered.'],
  ['Teleport', 7, 'C', 'bsw', '1 action', '10 ft.', 'V', 'Instantaneous', 'Transport yourself and up to eight companions any distance on the same plane.'],

  // ------------------------------------------------------------------ level 8
  ['Animal Shapes', 8, 'T', 'd', '1 action', '30 ft.', 'V, S', 'Concentration, up to 24 hours', 'Transform willing creatures into beasts of challenge rating 4 or lower.'],
  ['Antimagic Field', 8, 'A', 'cw', '1 action', 'Self (10-ft. radius)', 'V, S, M', 'Concentration, up to 1 hour', 'Magic simply does not function inside the sphere.'],
  ['Antipathy/Sympathy', 8, 'E', 'dw', '1 hour', '60 ft.', 'V, S, M', '10 days', 'Make a target repel or attract a chosen kind of creature.'],
  ['Clone', 8, 'N', 'w', '1 hour', 'Touch', 'V, S, M', 'Instantaneous', 'Grow a duplicate body that receives the original’s soul on death.'],
  ['Control Weather', 8, 'T', 'cdw', '10 minutes', 'Self (5-mile radius)', 'V, S, M', 'Concentration, up to 8 hours', 'Change precipitation, temperature, and wind for miles around.'],
  ['Demiplane', 8, 'C', 'skw', '1 action', '60 ft.', 'S', '1 hour', 'Open a door to a 30-foot room on a demiplane.'],
  ['Dominate Monster', 8, 'E', 'bskw', '1 action', '60 ft.', 'V, S', 'Concentration, up to 1 hour', 'Charm any creature and command it telepathically.'],
  ['Earthquake', 8, 'V', 'cds', '1 action', '500 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'A tremor knocks creatures prone, collapses structures, and opens fissures.'],
  ['Feeblemind', 8, 'V', 'bdkw', '1 action', '150 ft.', 'V, S, M', 'Instantaneous', '4d6 psychic damage and, on a failure, Intelligence and Charisma drop to 1.'],
  ['Glibness', 8, 'T', 'bk', '1 action', 'Self', 'V', '1 hour', 'Treat any Charisma check as a 15 or better, and no magic can detect your lies.'],
  ['Holy Aura', 8, 'A', 'c', '1 action', 'Self', 'V, S, M', 'Concentration, up to 1 minute', 'Allies gain advantage on saves, attackers have disadvantage, and fiends may be blinded.'],
  ['Incendiary Cloud', 8, 'C', 'sw', '1 action', '150 ft.', 'V, S', 'Concentration, up to 1 minute', 'A cloud of burning embers deals 10d8 fire damage and moves each turn.'],
  ['Maze', 8, 'C', 'w', '1 action', '60 ft.', 'V, S', 'Concentration, up to 10 minutes', 'Banish a creature into a labyrinthine demiplane until it escapes.'],
  ['Mind Blank', 8, 'A', 'bw', '1 action', 'Touch', 'V, S', '24 hours', 'Immunity to psychic damage, mind reading, divination, and charm.'],
  ['Power Word Stun', 8, 'E', 'bskw', '1 action', '60 ft.', 'V', 'Instantaneous', 'A creature with 150 hit points or fewer is stunned outright.'],
  ['Sunburst', 8, 'V', 'dsw', '1 action', '150 ft.', 'V, S, M', 'Instantaneous', 'Brilliant light deals 12d6 radiant damage and blinds in a 60-foot radius.'],
  ['Tsunami', 8, 'C', 'd', '1 minute', 'Sight', 'V, S', 'Concentration, up to 6 rounds', 'A wall of water 300 feet long crashes down for 6d10 bludgeoning damage.'],

  // ------------------------------------------------------------------ level 9
  ['Astral Projection', 9, 'N', 'ckw', '1 hour', '10 ft.', 'V, S, M', 'Special', 'Project your astral body to the Astral Plane along with companions.'],
  ['Foresight', 9, 'D', 'bdkw', '1 minute', 'Touch', 'V, S, M', '8 hours', 'The target cannot be surprised, has advantage on everything, and attackers have disadvantage.'],
  ['Gate', 9, 'C', 'cskw', '1 action', '60 ft.', 'V, S, M', 'Concentration, up to 1 minute', 'Open a portal to another plane and optionally pull a named creature through.'],
  ['Imprisonment', 9, 'A', 'kw', '1 minute', '30 ft.', 'V, S, M', 'Until dispelled', 'Bind a creature in a burial, chain, slumber, or minimus containment.'],
  ['Mass Heal', 9, 'V', 'c', '1 action', '60 ft.', 'V, S', 'Instantaneous', 'Distribute 700 hit points of healing and cure disease and blindness.'],
  ['Meteor Swarm', 9, 'V', 'sw', '1 action', '1 mile', 'V, S', 'Instantaneous', 'Four blazing spheres each deal 20d6 fire and 20d6 bludgeoning damage.'],
  ['Power Word Kill', 9, 'E', 'bskw', '1 action', '60 ft.', 'V', 'Instantaneous', 'A creature with 100 hit points or fewer simply dies.'],
  ['Prismatic Wall', 9, 'A', 'w', '1 action', '60 ft.', 'V, S', '10 minutes', 'Seven shimmering layers, each with its own deadly effect.'],
  ['Shapechange', 9, 'T', 'dw', '1 action', 'Self', 'V, S, M', 'Concentration, up to 1 hour', 'Assume the form of any creature of a challenge rating up to your level.'],
  ['Storm of Vengeance', 9, 'C', 'd', '1 action', 'Sight', 'V, S', 'Concentration, up to 1 minute', 'A storm escalates each round through acid, lightning, hail, and freezing wind.'],
  ['Time Stop', 9, 'T', 'sw', '1 action', 'Self', 'V', 'Instantaneous', 'Take 1d4 + 1 turns in a row while everything else stands still.'],
  ['True Polymorph', 9, 'T', 'bkw', '1 action', '30 ft.', 'V, S, M', 'Concentration, up to 1 hour', 'Turn a creature into another creature or an object, permanently if maintained.'],
  ['True Resurrection', 9, 'N', 'cd', '1 hour', 'Touch', 'V, S, M', 'Instantaneous', 'Return a creature dead up to 200 years to life, even without a body.'],
  ['Weird', 9, 'I', 'w', '1 action', '120 ft.', 'V, S', 'Concentration, up to 1 minute', 'Each creature in a 30-foot sphere sees its worst fear and takes 4d10 psychic damage each turn.'],
  ['Wish', 9, 'C', 'sw', '1 action', 'Self', 'V', 'Instantaneous', 'Duplicate any spell of 8th level or lower, or alter reality at some risk.'],
]

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[’']/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}

const entries: Entry[] = spells.map(([name, level, school, classes, time, range, components, duration, text]) => {
  const classList = classes.split('').map((letter) => CLASS_BY_LETTER[letter]).filter((value): value is string => !!value)
  const schoolName = SCHOOLS[school] ?? school
  const concentration = duration.startsWith('Concentration')

  return {
    id: slugify(name),
    name,
    summary: text,
    icon: level === 0 ? '✨' : undefined,
    tags: [...classList, `level-${level}`, schoolName.toLowerCase(), ...(concentration ? ['concentration'] : [])],
    meta: {
      level,
      School: schoolName,
      'Casting Time': time,
      Range: range,
      Components: components,
      Duration: duration,
    },
  }
})

export const spellCollection: Collection = {
  id: 'spells',
  label: 'Spells',
  singular: 'Spell',
  entries,
}

/** Human-readable label for a spell level, used by the UI and the PDF. */
export function spellLevelLabel(level: number): string {
  if (level === 0) return 'Cantrip'
  const suffix = level === 1 ? 'st' : level === 2 ? 'nd' : level === 3 ? 'rd' : 'th'
  return `${level}${suffix} level`
}
